### ISSUE TITLE
USB error? Works until detection starts.

### ISSUE THREAD

**Issue by kongjudas** [grinco/HASS-coral-rest-api#3]
Logging to /dev/null
Starting the server...
 Loaded engine with model : /app/models/tf2_ssd_mobilenet_v2_coco17_ptq_edgetpu.tflite
 * Serving Flask app 'coral-app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
F :1147] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
[cmd] /app/run.sh exited 262
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by grinco** [comment]
Are you running in a VM? If so - are you passing the USB device to the VM? The TPM needs to be used exclusively, do you have other software using it when you're trying to run it?

**Comment by kongjudas** [comment]
Yes, through Proxmox. I have Frigate using the TPU. Should I run CPU detector for Frigate?

**Comment by grinco** [comment]
You can't do both. Use CPU detector in Frigate, or stop it for the time that you're testing this addon.  As I said, TPU requires exclusive access.

**Comment by grinco** [comment]
I'll resolve this for now as it doesn't seem to be a bug.
