### ISSUE TITLE
Unable to add in HASS

### ISSUE THREAD

**Issue by leeyuentuen** [grinco/HASS-coral-rest-api#4]
I'm unable to add them in HASS
![afbeelding](https://user-images.githubusercontent.com/1487966/178155904-46cdfd1c-18f0-42e0-a6d9-4f1c214ae34b.png)

running Home Assistant 2022.7.2

**Comment by grinco** [comment]
This isn't a HACS integrations. Add it as HASS add-ons repository.

**Comment by grinco** [comment]
![Screenshot_2022-07-10-19-51-25-26_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/5553528/178156315-72226867-78c1-4855-8144-a8390383ca16.jpg)
