### ISSUE TITLE
installation fail with HASS on BLUE

### ISSUE THREAD

**Issue by alainvdu69** [grinco/HASS-coral-rest-api#5]
Hi !
Here the error i've got :

Échec de l'installation de l'extension
The command '/bin/bash -o pipefail -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

thx.

**Comment by alainvdu69** [comment]
it seem that the requirements.txt file is missing ?

**Comment by grinco** [comment]
I'm not including the python code with this container. It's built on installation time. The app is pulled from here: https://github.com/robmarkcole/coral-pi-rest-server/archive/refs/tags/v1.0.zip

It might simply not work on your specific environment.
