### ISSUE TITLE
Install fails on RPi4

### ISSUE THREAD

**Issue by longmover** [grinco/HASS-coral-rest-api#6]
System:
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

This message pops up after a few seconds when attempting to install:
failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

Log:
Failed to to call /addons/d44241f3_coral-api/install - failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

**Comment by grinco** [comment]
This might be related to the fact that I'm using x86 base image for this container: homeassistant/amd64-base-ubuntu:18.04

I'll need to think of a way to make this platform independent... Will try building it on one of my raspberries.

**Comment by Gfermoto** [comment]
d44241f3_coral-api - odroid n2+

**Comment by Levanterman** [comment]
Hi 

I have home assistant running on a Rpi4-64, I added the repository ok , but when i try and install it i get an error  :-( :

Failed to install add-on
The command '/bin/bash -o pipefail -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

<img width="745" alt="TPURest" src="https://user-images.githubusercontent.com/49679006/191627281-1acad10d-ee9e-4e7b-8ddb-de8a6cc3dc73.png">

**Comment by txprojects88** [comment]
> Hi 
> 
> 
> 
> I have home assistant running on a Rpi4-64, I added the repository ok , but when i try and install it i get an error  :-( :
> 
> 
> 
> Failed to install add-on
> 
> The command '/bin/bash -o pipefail -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
> 
> 
> 
> <img width="745" alt="TPURest" src="https://user-images.githubusercontent.com/49679006/191627281-1acad10d-ee9e-4e7b-8ddb-de8a6cc3dc73.png">
> 
> 

Having same issue :(

**Comment by grinco** [comment]
It probably has something to do with python 3.9 deprecation that has been announced in 2023.02. This addon uses an older version of 
https://github.com/robmarkcole/coral-pi-rest-server/. I'll have a look if I can run the latest one - based on guidance here: https://github.com/robmarkcole/coral-pi-rest-server/issues/66

I won't have time to look at it before Thursday however. So if anyone wants to have a look - please do.

**Comment by grinco** [comment]
I was wrong. I use an amd64 base image, so ARM builds will fail. I need to adjust the Dockerfile for multiarch support. Time constraints are the same so won't be able to look at it until later this week.

**Comment by grinco** [comment]
Please try now. I was able to build it on my radxa rock 5b, looks like bumping the base image to Ubuntu 20.04 LTS solved it. I haven't done proper testing, though - did what I could from a cell phone while waiting at the gate.

**Comment by grinco** [comment]
Confirmed working and bumped the release version up: https://github.com/grinco/HASS-coral-rest-api/tags
