### ISSUE TITLE
Any advice on how to run via separate docker instead of HASS supervised

### ISSUE THREAD

**Issue by skug67** [grinco/HASS-coral-rest-api#7]
I've got homeassistant installed using virtualenv.  I'd be interested in replacing deepstack with a Coral-enabled image recognition service, and I do have docker installed on the same machine -- but I don't know quite how to go about setting this up so that it won't go looking for a HASS supervised instance.  Can anyone point me in the right direction?

Thanks in advance.

**Comment by grinco** [comment]
You can't. Startup script relies on this container to be run as a HASS supervised container. You may want to build your own container and replace the variables in run.sh script with static entries or pass them over as environment variables.
