### ISSUE TITLE
Enable facial recognition?

### ISSUE THREAD

**Issue by fodi666** [grinco/HASS-coral-rest-api#8]
Hi,
thanks for the addon, works great with Blue Iris instance in a different VM. I have a suggestion, though: can you also enable facial recognition for Deepstack? I'm fine with having a config entry for enabling facial recognition if you think that is not needed for everyone. (it should be possible to add "VISION-FACE=True" to the existing query also can be added alongside "VISION-DETECTION=True"
Thanks

**Comment by grinco** [comment]
Two issues:
1. This addon deploys the [coral-pi-rest-server](https://github.com/robmarkcole/coral-pi-rest-server) that supports object detection only
2. Coral TPU can load only one model at once, so it can't do both model detection and facial recognition. 

While I supply the model dynamically to the integration, and could add an option to trigger face recognition, the underlying service doesn't support it.

I suggest you report your feature request [here](https://github.com/robmarkcole/coral-pi-rest-server/issues/new) and reopen this issue when the feature will be implemented.

**Comment by fodi666** [comment]
OK, fair enough, left a feature request over there.
